// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
declare global {
  interface Window {
    gtag: (...args: any[]) => void;
    dataLayer: any[];
  }
  namespace NodeJS {
    interface ProcessEnv {
      BUN_PUBLIC_GA_MEASUREMENT_ID: string;
      BUN_PUBLIC_SANITY_PROJECT_ID: string;
      BUN_PUBLIC_SANITY_DATASET: string;
      BUN_PUBLIC_SANITY_API_VERSION: string;
      BUN_PUBLIC_NUMBER: string;
    }
  }
}
